name: Build
permissions:
  id-token: write
  pages: write
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/andrewbaxter/somewords:latest
        with:
          args: /somewords "Andrew Baxter" https://github.com/andrewbaxter/5987/commit/
      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: pages
      - uses: actions/deploy-pages@v2
